# Generated by Django 6.1.1 on 2026-09-23 16:18

import people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, upload_to=people.models.photo_path),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_caption',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_thumbnail',
            field=models.FileField(blank=True, upload_to=people.models.photo_path),
        ),
    ]
