# Generated by Django 6.1.1 on 2026-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_hiddenperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='pronouns',
            field=models.CharField(blank=True, choices=[('she', 'she / her'), ('he', 'he / him'), ('they', 'they / them')], max_length=4),
        ),
    ]
