# Generated by Django 6.1.1 on 2026-10-02 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_person_pronouns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='kept_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='kept_from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='kept_space',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='AccessEnded',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('removed', 'Removed'), ('stopped_sharing', 'Stopped Sharing'), ('space_deleted', 'Space Deleted'), ('member_left', 'Member Left'), ('person_removed', 'Person Removed'), ('person_deleted', 'Person Deleted')], max_length=20)),
                ('by', models.CharField(max_length=200)),
                ('space', models.CharField(blank=True, max_length=100)),
                ('about', models.CharField(blank=True, max_length=200)),
                ('lost_count', models.PositiveIntegerField(help_text='People who left the book, kept or not.')),
                ('kept', models.ManyToManyField(blank=True, related_name='+', to='people.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'access ended',
                'ordering': ['-created_at'],
            },
        ),
    ]
