# Generated by Django 6.1.1 on 2026-10-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_kept_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessended',
            name='toasted',
            field=models.BooleanField(default=False),
        ),
    ]
