# Generated by Django 6.1.1 on 2026-10-08 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        ('people', '0009_access_ended_toasted'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='added_by_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='imports.import'),
        ),
    ]
