# Generated by Django 6.1.1 on 2026-10-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_merge'),
        ('people', '0010_person_added_by_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmethod',
            name='added_by_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='imports.import'),
        ),
    ]
