/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report whether the API is up and can reach the database.
         */
        get: operations["config_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Setup Status
         * @description Whether this server still needs its first account (the app shows setup).
         */
        get: operations["invites_api_setup_status"];
        put?: never;
        /**
         * First Run
         * @description Create the first account, as the server's admin, and log in.
         */
        post: operations["invites_api_first_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Csrf
         * @description Sets the `csrftoken` cookie. Send it back as the X-CSRFToken header on writes.
         */
        get: operations["accounts_api_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["accounts_api_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["accounts_api_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["accounts_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change your password. Signs you out on every other device.
         */
        post: operations["accounts_api_change_password"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Devices
         * @description Where you're signed in, most recently used first.
         */
        get: operations["accounts_api_list_devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign Out Device */
        delete: operations["accounts_api_sign_out_device"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/devices/sign-out-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign Out Other Devices */
        post: operations["accounts_api_sign_out_other_devices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Invites
         * @description Your invites; admins see every invite on the server.
         */
        get: operations["invites_api_list_invites"];
        put?: never;
        /**
         * Create Invite
         * @description Admins can invite anyone; anyone can invite people into a space they own.
         */
        post: operations["invites_api_create_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{invite_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invite */
        delete: operations["invites_api_revoke_invite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/by-token/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Invite */
        get: operations["invites_api_preview_invite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/by-token/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Invite
         * @description Create an account with the invite and log in.
         */
        post: operations["invites_api_accept_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/by-token/{token}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join With Invite
         * @description Already have an account? Join the invite's space with it.
         */
        post: operations["invites_api_join_with_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List People
         * @description Everyone the user can see, by name. `needs_details`: no "how we met" yet.
         *
         *     `search` matches names, how you met, work, tags, spaces and your own notes and
         *     memory aids, ignoring case and accents.
         */
        get: operations["people_api_list_people"];
        put?: never;
        /** Create Person */
        post: operations["people_api_create_person"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person */
        get: operations["people_api_get_person"];
        put?: never;
        post?: never;
        /** Delete Person */
        delete: operations["people_api_delete_person"];
        options?: never;
        head?: never;
        /** Update Person */
        patch: operations["people_api_update_person"];
        trace?: never;
    };
    "/api/people/{person_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Photo
         * @description The person's photo (WebP), for anyone who can see them.
         */
        get: operations["people_api_get_photo"];
        put?: never;
        /**
         * Upload Photo
         * @description Replace the photo. Any image the server can read; it's cropped to 4:5.
         */
        post: operations["people_api_upload_photo"];
        /** Delete Photo */
        delete: operations["people_api_delete_photo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{person_id}/family": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Family
         * @description Parents, siblings, cousins, in-laws, …, from the links the user can see.
         */
        get: operations["people_api_get_family"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{person_id}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Note
         * @description The user's own notes on this person (empty if none).
         */
        get: operations["people_api_get_note"];
        /**
         * Save Note
         * @description Replace the user's notes on this person. Empty text removes them.
         */
        put: operations["people_api_save_note"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Spaces */
        get: operations["spaces_api_list_spaces"];
        put?: never;
        /** Create Space */
        post: operations["spaces_api_create_space"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Space */
        get: operations["spaces_api_get_space"];
        put?: never;
        post?: never;
        /** Delete Space */
        delete: operations["spaces_api_delete_space"];
        options?: never;
        head?: never;
        /** Update Space */
        patch: operations["spaces_api_update_space"];
        trace?: never;
    };
    "/api/spaces/{space_id}/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Person
         * @description Put a person in a space. Adding someone who's already there does nothing.
         */
        post: operations["spaces_api_add_person"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spaces/{space_id}/people/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Person */
        delete: operations["spaces_api_remove_person"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Relationships
         * @description Stored links the user can see; `person` narrows to that person's links.
         */
        get: operations["relationships_api_list_relationships"];
        put?: never;
        /** Create Relationship */
        post: operations["relationships_api_create_relationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Relationship */
        get: operations["relationships_api_get_relationship"];
        put?: never;
        post?: never;
        /** Delete Relationship */
        delete: operations["relationships_api_delete_relationship"];
        options?: never;
        head?: never;
        /** Update Relationship */
        patch: operations["relationships_api_update_relationship"];
        trace?: never;
    };
    "/api/relationships/{link_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End Relationship
         * @description Mark a link as former (e.g. a divorce). Parent links never end.
         */
        post: operations["relationships_api_end_relationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relationships/{link_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen Relationship */
        post: operations["relationships_api_reopen_relationship"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph
         * @description Everyone the user can see and how they're connected.
         */
        get: operations["graph_api_get_graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/neighborhood/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Neighborhood
         * @description Focus mode: a person and everyone within 1 or 2 steps.
         */
        get: operations["graph_api_get_neighborhood"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph/paths/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Paths
         * @description How do I know …? Routes from the user's Me to this person.
         */
        get: operations["graph_api_get_paths"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory-aids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Memory Aids
         * @description The user's own sticky notes, pinned first; `person` narrows to one person.
         */
        get: operations["people_api_list_memory_aids"];
        put?: never;
        /** Create Memory Aid */
        post: operations["people_api_create_memory_aid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory-aids/{aid_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Memory Aid */
        delete: operations["people_api_delete_memory_aid"];
        options?: never;
        head?: never;
        /** Update Memory Aid */
        patch: operations["people_api_update_memory_aid"];
        trace?: never;
    };
    "/api/interactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Interactions
         * @description The user's own timeline, newest first; `person` narrows to one person.
         */
        get: operations["interactions_api_list_interactions"];
        put?: never;
        /** Log Interaction */
        post: operations["interactions_api_log_interaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interactions/{interaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Interaction */
        delete: operations["interactions_api_delete_interaction"];
        options?: never;
        head?: never;
        /** Update Interaction */
        patch: operations["interactions_api_update_interaction"];
        trace?: never;
    };
    "/api/keep-in-touch/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Keep In Touch
         * @description The user's own setting; defaults when there is none yet.
         */
        get: operations["reminders_api_get_keep_in_touch"];
        /** Save Keep In Touch */
        put: operations["reminders_api_save_keep_in_touch"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** SetupStatusOut */
        SetupStatusOut: {
            /** Needed */
            needed: boolean;
        };
        /** CurrentUserOut */
        CurrentUserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Is Admin */
            is_admin: boolean;
            me: components["schemas"]["PersonRef"] | null;
        };
        /** PersonRef */
        PersonRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** SignUpIn */
        SignUpIn: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** CsrfOut */
        CsrfOut: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** ErrorOut */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Remember
             * @default true
             */
            remember?: boolean;
        };
        /** PasswordIn */
        PasswordIn: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** Input */
        Input: {
            /**
             * Page
             * @default 1
             */
            page?: number;
            /** Page Size */
            page_size?: number | null;
        };
        /** DeviceOut */
        DeviceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Device */
            device: string;
            /** Ip */
            ip: string | null;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen: string;
            /** Is Current */
            is_current: boolean;
        };
        /** PagedDeviceOut */
        PagedDeviceOut: {
            /** Items */
            items: components["schemas"]["DeviceOut"][];
            /** Count */
            count: number;
        };
        /**
         * Color
         * @enum {string}
         */
        Color: "sage" | "ochre" | "clay" | "plum" | "teal" | "slate";
        /** InviteOut */
        InviteOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Token */
            token: string;
            /** Path */
            path: string;
            created_by: components["schemas"]["PersonRef"] | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Max Uses */
            max_uses: number;
            /** Uses */
            uses: number;
            /** Is Usable */
            is_usable: boolean;
            space: components["schemas"]["SpaceRef"] | null;
            role: components["schemas"]["Role"];
        };
        /** PagedInviteOut */
        PagedInviteOut: {
            /** Items */
            items: components["schemas"]["InviteOut"][];
            /** Count */
            count: number;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "editor" | "viewer";
        /** SpaceRef */
        SpaceRef: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            color: components["schemas"]["Color"];
        };
        /** InviteIn */
        InviteIn: {
            /**
             * Expires In Days
             * @default 7
             */
            expires_in_days?: number;
            /**
             * Max Uses
             * @default 1
             */
            max_uses?: number;
            /** Space Id */
            space_id?: string | null;
            /** @default viewer */
            role?: components["schemas"]["Role"];
        };
        /**
         * InvitePreviewOut
         * @description What someone opening an invite link sees before signing up.
         */
        InvitePreviewOut: {
            /** Invited By */
            invited_by: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            space: components["schemas"]["SpaceRef"] | null;
            /** Space People Count */
            space_people_count: number | null;
            role: components["schemas"]["Role"];
        };
        /** Birthday */
        Birthday: {
            /** Day */
            day: number;
            /** Month */
            month: number;
            /** Year */
            year?: number | null;
        };
        /** PagedPersonOut */
        PagedPersonOut: {
            /** Items */
            items: components["schemas"]["PersonOut"][];
            /** Count */
            count: number;
        };
        /**
         * PersonOut
         * @description The basic profile, as the viewer is allowed to see it.
         */
        PersonOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** How We Met */
            how_we_met: string;
            /** Work */
            work: string;
            birthday: components["schemas"]["Birthday"] | null;
            /** Tags */
            tags: string[];
            /** Spaces */
            spaces: components["schemas"]["SpaceRef"][];
            /** Is Me */
            is_me: boolean;
            /** Is Mine */
            is_mine: boolean;
            owner: components["schemas"]["PersonRef"] | null;
            photo: components["schemas"]["PhotoOut"] | null;
            /** Needs Details */
            needs_details: boolean;
            /** Last Talked On */
            last_talked_on: string | null;
        };
        /** PhotoOut */
        PhotoOut: {
            /** Url */
            url: string;
            /** Thumbnail Url */
            thumbnail_url: string;
            /** Caption */
            caption: string;
        };
        /**
         * ContactKind
         * @enum {string}
         */
        ContactKind: "phone" | "email" | "social" | "other";
        /** ContactMethodOut */
        ContactMethodOut: {
            kind: components["schemas"]["ContactKind"];
            /**
             * Label
             * @default
             */
            label?: string;
            /** Value */
            value: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** PersonDetailOut */
        PersonDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** How We Met */
            how_we_met: string;
            /** Work */
            work: string;
            birthday: components["schemas"]["Birthday"] | null;
            /** Tags */
            tags: string[];
            /** Spaces */
            spaces: components["schemas"]["SpaceRef"][];
            /** Is Me */
            is_me: boolean;
            /** Is Mine */
            is_mine: boolean;
            owner: components["schemas"]["PersonRef"] | null;
            photo: components["schemas"]["PhotoOut"] | null;
            /** Needs Details */
            needs_details: boolean;
            /** Last Talked On */
            last_talked_on: string | null;
            /** Contact Methods */
            contact_methods: components["schemas"]["ContactMethodOut"][];
            /** Can Edit */
            can_edit: boolean;
            /** Can Delete */
            can_delete: boolean;
        };
        /** ContactMethodIn */
        ContactMethodIn: {
            kind: components["schemas"]["ContactKind"];
            /**
             * Label
             * @default
             */
            label?: string;
            /** Value */
            value: string;
        };
        /** PersonIn */
        PersonIn: {
            /** Name */
            name: string;
            /**
             * How We Met
             * @default
             */
            how_we_met?: string;
            /**
             * Work
             * @default
             */
            work?: string;
            birthday?: components["schemas"]["Birthday"] | null;
            /**
             * Tags
             * @default []
             */
            tags?: string[];
            /**
             * Contact Methods
             * @default []
             */
            contact_methods?: components["schemas"]["ContactMethodIn"][];
            /**
             * Space Ids
             * @default []
             */
            space_ids?: string[];
            /**
             * Photo Caption
             * @default
             */
            photo_caption?: string;
        };
        /**
         * PersonPatch
         * @description Only the fields sent are changed. Tags and contact details: owner only.
         */
        PersonPatch: {
            /** Name */
            name?: string | null;
            /** How We Met */
            how_we_met?: string | null;
            /** Work */
            work?: string | null;
            birthday?: components["schemas"]["Birthday"] | null;
            /** Tags */
            tags?: string[] | null;
            /** Contact Methods */
            contact_methods?: components["schemas"]["ContactMethodIn"][] | null;
            /** Space Ids */
            space_ids?: string[] | null;
            /** Photo Caption */
            photo_caption?: string | null;
        };
        /** FamilyRelationOut */
        FamilyRelationOut: {
            person: components["schemas"]["PersonRef"];
            /** Relation */
            relation: string;
            /** Derived */
            derived: boolean;
            /** Former */
            former: boolean;
            parent_type: components["schemas"]["ParentType"] | null;
            /** Direct Link Id */
            direct_link_id: string | null;
        };
        /**
         * ParentType
         * @enum {string}
         */
        ParentType: "biological" | "adoptive" | "step";
        /**
         * NoteOut
         * @description The user's own notes on a person; never anyone else's.
         */
        NoteOut: {
            /** Body */
            body: string;
            /** Updated At */
            updated_at: string | null;
        };
        /** NoteIn */
        NoteIn: {
            /** Body */
            body: string;
        };
        /** PagedSpaceOut */
        PagedSpaceOut: {
            /** Items */
            items: components["schemas"]["SpaceOut"][];
            /** Count */
            count: number;
        };
        /** SpaceOut */
        SpaceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            color: components["schemas"]["Color"];
            /** Description */
            description: string;
            /** Share Contact Details */
            share_contact_details: boolean;
            /** Role */
            role: string;
            owner: components["schemas"]["PersonRef"] | null;
            /** People Count */
            people_count: number;
            /** Member Count */
            member_count: number;
        };
        /** SpaceIn */
        SpaceIn: {
            /** Name */
            name: string;
            /** @default sage */
            color?: components["schemas"]["Color"];
            /**
             * Description
             * @default
             */
            description?: string;
        };
        /** SpacePatch */
        SpacePatch: {
            /** Name */
            name?: string | null;
            color?: components["schemas"]["Color"] | null;
            /** Description */
            description?: string | null;
            /** Share Contact Details */
            share_contact_details?: boolean | null;
        };
        /** SpacePersonIn */
        SpacePersonIn: {
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
        };
        /** PagedRelationshipOut */
        PagedRelationshipOut: {
            /** Items */
            items: components["schemas"]["RelationshipOut"][];
            /** Count */
            count: number;
        };
        /**
         * RelationshipOut
         * @description A stored link. Directional types read "person_a is the <type> of person_b".
         */
        RelationshipOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            person_a: components["schemas"]["PersonRef"];
            person_b: components["schemas"]["PersonRef"];
            type: components["schemas"]["RelationshipType"];
            parent_type: components["schemas"]["ParentType"] | null;
            /** Label */
            label: string;
            /** Started On */
            started_on: string | null;
            /** Ended On */
            ended_on: string | null;
            /** Is Former */
            is_former: boolean;
            space: components["schemas"]["SpaceRef"] | null;
            /** Is Mine */
            is_mine: boolean;
        };
        /**
         * RelationshipType
         * @enum {string}
         */
        RelationshipType: "parent" | "partner" | "sibling" | "cousin" | "grandparent" | "aunt_uncle" | "friend" | "colleague" | "classmate" | "met_at" | "custom";
        /**
         * RelationshipIn
         * @description For directional types, `person_a` is the parent / grandparent / aunt or uncle.
         */
        RelationshipIn: {
            /**
             * Person A Id
             * Format: uuid
             */
            person_a_id: string;
            /**
             * Person B Id
             * Format: uuid
             */
            person_b_id: string;
            type: components["schemas"]["RelationshipType"];
            parent_type?: components["schemas"]["ParentType"] | null;
            /**
             * Label
             * @default
             */
            label?: string;
            /** Started On */
            started_on?: string | null;
            /** Space Id */
            space_id?: string | null;
        };
        /** RelationshipPatch */
        RelationshipPatch: {
            parent_type?: components["schemas"]["ParentType"] | null;
            /** Label */
            label?: string | null;
            /** Started On */
            started_on?: string | null;
        };
        /** EndIn */
        EndIn: {
            /** Ended On */
            ended_on?: string | null;
        };
        /**
         * EdgeKind
         * @enum {string}
         */
        EdgeKind: "relationship" | "space" | "member";
        /**
         * GraphEdgeOut
         * @description A connection. `type`/`label` are set for stored links, `space` for space edges.
         */
        GraphEdgeOut: {
            /** Id */
            id: string;
            /**
             * Source
             * Format: uuid
             */
            source: string;
            /**
             * Target
             * Format: uuid
             */
            target: string;
            kind: components["schemas"]["EdgeKind"];
            /** Type */
            type: string | null;
            /** Label */
            label: string;
            /** Former */
            former: boolean;
            space: components["schemas"]["SpaceRef"] | null;
        };
        /** GraphNodeOut */
        GraphNodeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Is Me */
            is_me: boolean;
            /** Spaces */
            spaces: components["schemas"]["SpaceRef"][];
        };
        /** GraphOut */
        GraphOut: {
            /** Nodes */
            nodes: components["schemas"]["GraphNodeOut"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeOut"][];
        };
        /** NeighborhoodParams */
        NeighborhoodParams: {
            /**
             * Hops
             * @default 1
             */
            hops?: number;
        };
        /** PathParams */
        PathParams: {
            /**
             * Alternatives
             * @default 2
             */
            alternatives?: number;
        };
        /** HopOut */
        HopOut: {
            source: components["schemas"]["PersonRef"];
            target: components["schemas"]["PersonRef"];
            kind: components["schemas"]["EdgeKind"];
            /** Type */
            type: string | null;
            /** Label */
            label: string;
            space: components["schemas"]["SpaceRef"] | null;
        };
        /** PathOut */
        PathOut: {
            /** Hops */
            hops: components["schemas"]["HopOut"][];
        };
        /**
         * PathsOut
         * @description The shortest route first, then alternatives with a different first step.
         */
        PathsOut: {
            /** Paths */
            paths: components["schemas"]["PathOut"][];
        };
        /** MemoryAidOut */
        MemoryAidOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Text */
            text: string;
            /** Pinned */
            pinned: boolean;
            /** Position */
            position: number;
        };
        /** PagedMemoryAidOut */
        PagedMemoryAidOut: {
            /** Items */
            items: components["schemas"]["MemoryAidOut"][];
            /** Count */
            count: number;
        };
        /** MemoryAidIn */
        MemoryAidIn: {
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Text */
            text: string;
            /**
             * Pinned
             * @default false
             */
            pinned?: boolean;
        };
        /** MemoryAidPatch */
        MemoryAidPatch: {
            /** Text */
            text?: string | null;
            /** Pinned */
            pinned?: boolean | null;
            /** Position */
            position?: number | null;
        };
        /**
         * InteractionKind
         * @enum {string}
         */
        InteractionKind: "met" | "call" | "message" | "event" | "custom";
        /** InteractionOut */
        InteractionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            kind: components["schemas"]["InteractionKind"];
            /** Label */
            label: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Note */
            note: string;
        };
        /** PagedInteractionOut */
        PagedInteractionOut: {
            /** Items */
            items: components["schemas"]["InteractionOut"][];
            /** Count */
            count: number;
        };
        /** InteractionIn */
        InteractionIn: {
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            kind: components["schemas"]["InteractionKind"];
            /**
             * Label
             * @default
             */
            label?: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /**
             * Note
             * @default
             */
            note?: string;
        };
        /** InteractionPatch */
        InteractionPatch: {
            kind?: components["schemas"]["InteractionKind"] | null;
            /** Label */
            label?: string | null;
            /** Occurred On */
            occurred_on?: string | null;
            /** Note */
            note?: string | null;
        };
        /**
         * KeepInTouchSchema
         * @description The user's keep-in-touch setting for one person.
         */
        KeepInTouchSchema: {
            /** Interval Days */
            interval_days?: number | null;
            /** Snoozed Until */
            snoozed_until?: string | null;
            /**
             * Stopped
             * @default false
             */
            stopped?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    config_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    invites_api_setup_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
        };
    };
    invites_api_first_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserOut"];
                };
            };
        };
    };
    accounts_api_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfOut"];
                };
            };
        };
    };
    accounts_api_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    accounts_api_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserOut"];
                };
            };
        };
    };
    accounts_api_change_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordIn"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_api_list_devices: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedDeviceOut"];
                };
            };
        };
    };
    accounts_api_sign_out_device: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_api_sign_out_other_devices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invites_api_list_invites: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedInviteOut"];
                };
            };
        };
    };
    invites_api_create_invite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOut"];
                };
            };
        };
    };
    invites_api_revoke_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invite_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    invites_api_preview_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreviewOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    invites_api_accept_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    invites_api_join_with_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceRef"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    people_api_list_people: {
        parameters: {
            query?: {
                space?: string | null;
                needs_details?: boolean;
                search?: string;
                page?: number;
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedPersonOut"];
                };
            };
        };
    };
    people_api_create_person: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailOut"];
                };
            };
        };
    };
    people_api_get_person: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailOut"];
                };
            };
        };
    };
    people_api_delete_person: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    people_api_update_person: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailOut"];
                };
            };
        };
    };
    people_api_get_photo: {
        parameters: {
            query?: {
                size?: "full" | "thumbnail";
            };
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    people_api_upload_photo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailOut"];
                };
            };
        };
    };
    people_api_delete_photo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailOut"];
                };
            };
        };
    };
    people_api_get_family: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyRelationOut"][];
                };
            };
        };
    };
    people_api_get_note: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
        };
    };
    people_api_save_note: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
        };
    };
    spaces_api_list_spaces: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedSpaceOut"];
                };
            };
        };
    };
    spaces_api_create_space: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpaceIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceOut"];
                };
            };
        };
    };
    spaces_api_get_space: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceOut"];
                };
            };
        };
    };
    spaces_api_delete_space: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    spaces_api_update_space: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpacePatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpaceOut"];
                };
            };
        };
    };
    spaces_api_add_person: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpacePersonIn"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    spaces_api_remove_person: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                space_id: string;
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    relationships_api_list_relationships: {
        parameters: {
            query?: {
                person?: string | null;
                family?: boolean | null;
                page?: number;
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedRelationshipOut"];
                };
            };
        };
    };
    relationships_api_create_relationship: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipOut"];
                };
            };
        };
    };
    relationships_api_get_relationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipOut"];
                };
            };
        };
    };
    relationships_api_delete_relationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    relationships_api_update_relationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipOut"];
                };
            };
        };
    };
    relationships_api_end_relationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipOut"];
                };
            };
        };
    };
    relationships_api_reopen_relationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationshipOut"];
                };
            };
        };
    };
    graph_api_get_graph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOut"];
                };
            };
        };
    };
    graph_api_get_neighborhood: {
        parameters: {
            query?: {
                hops?: number;
            };
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphOut"];
                };
            };
        };
    };
    graph_api_get_paths: {
        parameters: {
            query?: {
                alternatives?: number;
            };
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PathsOut"];
                };
            };
        };
    };
    people_api_list_memory_aids: {
        parameters: {
            query?: {
                person?: string | null;
                page?: number;
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedMemoryAidOut"];
                };
            };
        };
    };
    people_api_create_memory_aid: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryAidIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryAidOut"];
                };
            };
        };
    };
    people_api_delete_memory_aid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aid_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    people_api_update_memory_aid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aid_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryAidPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryAidOut"];
                };
            };
        };
    };
    interactions_api_list_interactions: {
        parameters: {
            query?: {
                person?: string | null;
                page?: number;
                page_size?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedInteractionOut"];
                };
            };
        };
    };
    interactions_api_log_interaction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteractionIn"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionOut"];
                };
            };
        };
    };
    interactions_api_delete_interaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    interactions_api_update_interaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interaction_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteractionPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractionOut"];
                };
            };
        };
    };
    reminders_api_get_keep_in_touch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeepInTouchSchema"];
                };
            };
        };
    };
    reminders_api_save_keep_in_touch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeepInTouchSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeepInTouchSchema"];
                };
            };
        };
    };
}
