# Generated by Django 6.1.1 on 2026-09-23 08:00

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_person_birth_day_person_birth_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('sage', 'Sage'), ('ochre', 'Ochre'), ('clay', 'Clay'), ('plum', 'Plum'), ('teal', 'Teal'), ('slate', 'Slate')], default='sage', max_length=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('share_contact_details', models.BooleanField(default=False, help_text='Let members see phone numbers and email addresses.')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_spaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpacePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space')),
            ],
        ),
        migrations.AddField(
            model_name='space',
            name='people',
            field=models.ManyToManyField(related_name='spaces', through='spaces.SpacePerson', to='people.person'),
        ),
        migrations.CreateModel(
            name='SpaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='spaces.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('space', 'user'), name='spaces_member_once_per_space')],
            },
        ),
        migrations.AddConstraint(
            model_name='spaceperson',
            constraint=models.UniqueConstraint(fields=('space', 'person'), name='spaces_person_once_per_space'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(models.F('owner'), django.db.models.functions.text.Lower('name'), name='spaces_space_name_unique_per_owner'),
        ),
    ]
