# Generated by Django 6.1.1 on 2026-10-08 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('hashed', models.CharField(max_length=64, unique=True)),
                ('last_five', models.CharField(max_length=5)),
                ('read_only', models.BooleanField(default=True)),
                ('include_private', models.BooleanField(default=False)),
                ('limited', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_count', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
                ('spaces', models.ManyToManyField(blank=True, related_name='+', to='spaces.space')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
