# Generated by Django 6.1.1 on 2026-09-23 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_person_birth_day_person_birth_month_and_more'),
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('parent', 'Parent'), ('partner', 'Partner'), ('sibling', 'Sibling'), ('cousin', 'Cousin'), ('grandparent', 'Grandparent'), ('aunt_uncle', 'Aunt / uncle'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('classmate', 'Classmate'), ('met_at', 'Met at'), ('custom', 'Custom')], max_length=20)),
                ('parent_type', models.CharField(blank=True, choices=[('biological', 'Biological'), ('adoptive', 'Adoptive'), ('step', 'Step')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('is_former', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to=settings.AUTH_USER_MODEL)),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='people.person')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationships', to='spaces.space')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('person_a', models.F('person_b')), _negated=True), name='relationships_not_with_self'), models.CheckConstraint(condition=models.Q(('type__in', ['aunt_uncle', 'grandparent', 'parent']), ('person_a__lt', models.F('person_b')), _connector='OR'), name='relationships_symmetric_stored_once'), models.CheckConstraint(condition=models.Q(models.Q(('parent_type__in', ['biological', 'adoptive', 'step']), ('type', 'parent')), models.Q(models.Q(('type', 'parent'), _negated=True), ('parent_type', '')), _connector='OR'), name='relationships_parent_type_only_on_parents'), models.CheckConstraint(condition=models.Q(models.Q(('type__in', ['custom', 'met_at']), _negated=True), models.Q(('label', ''), _negated=True), _connector='OR'), name='relationships_label_required'), models.CheckConstraint(condition=models.Q(('is_former', True), ('type', 'parent'), _negated=True), name='relationships_parent_links_never_end'), models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('is_former', True), _connector='OR'), name='relationships_end_date_means_former'), models.UniqueConstraint(condition=models.Q(('is_former', False)), fields=('owner', 'person_a', 'person_b', 'type'), name='relationships_one_current_link_per_type')],
            },
        ),
    ]
