# Generated by Django 6.1.1 on 2026-09-23 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_birth_day_person_birth_month_and_more'),
        ('relationships', '0001_initial'),
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='relationship',
            name='relationships_not_with_self',
            constraint=models.CheckConstraint(condition=models.Q(('person_a', models.F('person_b')), _negated=True), name='relationships_not_with_self', violation_error_message="A person can't be linked to themselves."),
        ),
        migrations.AlterConstraint(
            model_name='relationship',
            name='relationships_parent_type_only_on_parents',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent_type__in', ['biological', 'adoptive', 'step']), ('type', 'parent')), models.Q(models.Q(('type', 'parent'), _negated=True), ('parent_type', '')), _connector='OR'), name='relationships_parent_type_only_on_parents', violation_error_message='Parent links need a parent type (biological, adoptive or step), and only parent links have one.'),
        ),
        migrations.AlterConstraint(
            model_name='relationship',
            name='relationships_label_required',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type__in', ['custom', 'met_at']), _negated=True), models.Q(('label', ''), _negated=True), _connector='OR'), name='relationships_label_required', violation_error_message='“Met at” and custom links need a label.'),
        ),
        migrations.AlterConstraint(
            model_name='relationship',
            name='relationships_parent_links_never_end',
            constraint=models.CheckConstraint(condition=models.Q(('is_former', True), ('type', 'parent'), _negated=True), name='relationships_parent_links_never_end', violation_error_message='Parent links never end.'),
        ),
        migrations.AlterConstraint(
            model_name='relationship',
            name='relationships_end_date_means_former',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('is_former', True), _connector='OR'), name='relationships_end_date_means_former', violation_error_message='Only ended links have an end date.'),
        ),
        migrations.AlterConstraint(
            model_name='relationship',
            name='relationships_one_current_link_per_type',
            constraint=models.UniqueConstraint(condition=models.Q(('is_former', False)), fields=('owner', 'person_a', 'person_b', 'type'), name='relationships_one_current_link_per_type', violation_error_message='This link already exists.'),
        ),
    ]
