# Generated by Django 6.1.1 on 2026-10-08 17:20

from django.db import migrations, models


def count_earlier_imports(apps, schema_editor):
    """Imports made before the counts were kept: count what's left of them, and call them
    finished when they were made."""
    Import = apps.get_model("imports", "Import")
    for batch in Import.objects.all():
        batch.added = batch.people.count()
        batch.merged = batch.merges.count()
        batch.finished_at = batch.created_at
        batch.save(update_fields=["added", "merged", "finished_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='import',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='merged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merge',
            name='taken_back',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(count_earlier_imports, migrations.RunPython.noop),
    ]
