# Generated by Django 6.1.1 on 2026-10-08 17:20

import datetime

from django.db import migrations, models
from django.db.models import Max


def count_earlier_imports(apps, schema_editor):
    """Imports made before the counts were kept: count what's left of them, and find when
    they finished. The import row came first, then its people, notes and merges, so it
    finished when the last of those was written (any import took well under a minute)."""
    Import = apps.get_model("imports", "Import")
    Note = apps.get_model("people", "Note")
    for batch in Import.objects.all():
        batch.added = batch.people.count()
        batch.merged = batch.merges.count()
        notes = Note.objects.filter(
            author_id=batch.owner_id,
            person__added_by_import=batch,
            created_at__lt=batch.created_at + datetime.timedelta(minutes=1),
        )
        written = [
            batch.people.aggregate(last=Max("created_at"))["last"],
            batch.merges.aggregate(last=Max("created_at"))["last"],
            notes.aggregate(last=Max("created_at"))["last"],
        ]
        batch.finished_at = max([batch.created_at, *filter(None, written)])
        batch.save(update_fields=["added", "merged", "finished_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='import',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='merged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merge',
            name='taken_back',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(count_earlier_imports, migrations.RunPython.noop),
    ]
