# Generated by Django 6.1.1 on 2026-09-23 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_person_birth_day_person_birth_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeepInTouch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interval_days', models.PositiveSmallIntegerField(blank=True, help_text="Empty means the user's default interval.", null=True)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('stopped', models.BooleanField(default=False, help_text='“Stop reminding me”.')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keep_in_touch', to='people.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'keep in touch settings',
                'constraints': [models.UniqueConstraint(fields=('user', 'person'), name='reminders_one_per_person'), models.CheckConstraint(condition=models.Q(('interval_days__isnull', True), ('interval_days__gte', 1), _connector='OR'), name='reminders_interval_positive')],
            },
        ),
    ]
