# Generated by Django 6.1.1 on 2026-10-01 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nudges_on', models.BooleanField(default=True, help_text='Keep-in-touch nudges on Today.')),
                ('default_interval_days', models.PositiveSmallIntegerField(blank=True, help_text='For people without their own interval. Empty: only those with one.', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'reminder settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('default_interval_days__isnull', True), ('default_interval_days__gte', 1), _connector='OR'), name='reminders_default_interval_positive')],
            },
        ),
    ]
