# Generated by Django 6.1.1 on 2026-09-23 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0002_person_birth_day_person_birth_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('met', 'Met'), ('call', 'Call'), ('message', 'Message'), ('event', 'Event'), ('custom', 'Custom')], max_length=10)),
                ('label', models.CharField(blank=True, help_text='Title, e.g. “Coffee”.', max_length=100)),
                ('occurred_on', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='people.person')),
            ],
            options={
                'ordering': ['-occurred_on', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'custom'), _negated=True), models.Q(('label', ''), _negated=True), _connector='OR'), name='interactions_custom_needs_label')],
            },
        ),
    ]
