# Generated by Django 6.1.1 on 2026-10-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-occurred_on', models.OrderBy(models.F('occurred_at'), descending=True, nulls_last=True), '-created_at']},
        ),
        migrations.AddField(
            model_name='interaction',
            name='occurred_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
