# Generated by Django 6.1.1 on 2026-09-23 10:43

import django.db.models.deletion
import invites.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=invites.models.new_token, editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('max_uses', models.PositiveSmallIntegerField(default=1)),
                ('uses', models.PositiveSmallIntegerField(default=0)),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_created', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='spaces.space')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('max_uses__gte', 1)), name='invites_at_least_one_use'), models.CheckConstraint(condition=models.Q(('uses__lte', models.F('max_uses'))), name='invites_not_used_more_than_allowed')],
            },
        ),
    ]
